server {
    listen 80;
    listen [::]:80;

    root /usr/share/nginx/html;

    # HIER die Standard-Indexdateien festlegen
    index login.html main.html; 

    location / {
        try_files $uri $uri/ =404;
    }
}