# .github/workflows/deploy.yml
name: Auto Deployment aetherus.net

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    
      - name: ⬇️ Checkout Code
        uses: actions/checkout@v4

      - name: 🚀 Deployment auf Ubuntu-Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }} 
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            PROJECT_DIR="/home/aetherus"
            
            # Wechselt temporär den Remote-URL auf HTTPS mit dem Secret Token, 
            # zieht die Daten und wechselt zurück auf SSH (zur Sicherheit).
            
            # Syntax: https://TOKEN@github.com/USER/REPO.git
            
            # 1. Korrigieren Sie hier Ihren BENUTZERNAMEN und REPO-NAMEN
            REPO_URL="https://${{ secrets.AETHERUS_DEPLOY_TOKEN }}@github.com/IhrGitHubBenutzername/IhrRepoName.git"
            
            # 2. PULL ausführen
            git -C $PROJECT_DIR pull $REPO_URL main
            
            # 3. Docker Compose neu starten
            cd $PROJECT_DIR
            docker compose up -d --force-recreate